CREATE TABLE `tbb_transacciones` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Descripción: Atributo numérico autoincremental que distingue de manera única a la transacción realizada por o hacia un usuario.\nNaturaleza: Cuantitativo.\nDominio: Entero Positivo.\nComposición: 1{0-1}',
  `usuario_id` int NOT NULL COMMENT 'Descripción: Atributo numérico que identifica de manera única a un usuario del gimnasio que realiza o se le realiza la transacción.\\nNaturaleza: Cuantitativo.\\nDominio: Entero Positivo.\\nComposición: 1{0-1}',
  `detalles` varchar(255) NOT NULL COMMENT 'Descripción: Información redacta la razón de una transacción.\\\\\\\\nNaturaleza: Cualitativo\\\\\\\\nDominio: Caracteres alfanuméricos\\\\\\\\nComposición: 1{A-z|0-9|'' ''}255',
  `tipo_transaccion` enum('INGRESO','EGRESO') NOT NULL COMMENT 'Descripción: Indica si la transacción corresponde a un ingreso o un egreso de dinero.\\nNaturaleza: Cualitativo.\\nDominio: Conjunto de valores permitidos.\\nComposición: [''Ingreso'',''Egreso'']',
  `metodo_pago` enum('TARJETA_DEBITO','TARJETA_CREDITO','EFECTIVO','TRANSFERENCIA') NOT NULL COMMENT 'Descripción: Almacena la información de pago de un usuario o cliente.\\nNaturaleza: Cualitativo.\\nDominio: Conjunto de valores predeterminados.\\nComposición: [''TARJETA_DEBITO'', ''TARJETA_CREDITO'', ''EFECTIVO'',''TRANSFERENCIA'']',
  `monto` float NOT NULL COMMENT 'Descripción: Determina la cantidad monetaria a pagar por un usuario.\\nNaturaleza: Cuantitativo.\\nDominio: Números enteros, números decimales y punto.\\nComposición: Número_entero = 1{0-9}10\\nPunto_decimal = [.]\\nNúmero_decimal = 0{0-9}2\\nMonto = Número_entero + Punto + Número_decimal',
  `estatus` enum('PROCESANDO','PAGADA','CANCELADA','RECHAZADA') NOT NULL COMMENT 'Descripción: Dato de auditoría que define el estatus de la transacción.\nNaturaleza: Cualitativo.\nDominio: Conjunto de valores permitidos.\nComposición: [''Cancelada'', ''Pagada'', ''Procesando'']',
  `fecha_registro` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de creacion del registro\\\\\\\\\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\\\\\\\\\nComposicion:\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\nAño = 4{0-9}4\\\\\\\\\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\nHora = [00|01|...|23]\\\\\\\\\\\\\\\\nMinutos = [00|01|...|59]\\\\\\\\\\\\\\\\nSeguntodos = [00|01|...|59]\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\nFecha_Registro= Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  `fecha_actualizacion` datetime DEFAULT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de la ultima modificacion del registro\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\nComposicion:\\\\\\\\n\\\\\\\\n\\\\\\\\nAño = 4{0-9}4\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\n\\\\\\\\nHora = [00|01|...|23]\\\\\\\\nMinutos = [00|01|...|59]\\\\\\\\nSeguntodos = [00|01|...|59]\\\\\\\\n\\\\\\\\nFecha_Actualizacion = Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  PRIMARY KEY (`id`),
  KEY `usuario_id` (`usuario_id`),
  KEY `ix_tbb_transacciones_id` (`id`),
  CONSTRAINT `tbb_transacciones_ibfk_1` FOREIGN KEY (`usuario_id`) REFERENCES `tbb_usuarios` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41835 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Registra las operaciones financieras o movimientos dentro del sistema, como pagos o compras. Cada transacción está asociada a un usuario que la realiza.';
