CREATE TABLE `tbb_usuarios` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Descripcion: Atributo identificador numero auto incremental que distingue de manera unica al usuario.\\nNaturaleza: Cuantitativo\\nDominio: Enteos positivos\\nComposicion: 1{0-9}',
  `persona_id` int NOT NULL COMMENT 'Descripcion: Identificador de la persona asociada al cliente. Relaciona con la tabla tbb_personas.\\\\nNaturaleza: Cuantitativa\\\\nDominio: Enteros positivos\\\\nComposicion: 1{0-9}',
  `nombre_usuario` varchar(60) NOT NULL COMMENT 'Descripción: Nombre que es generado por el sistema y asignado a una persona.\\\\nNaturaleza: Cualitativo\\\\nDominio: Cadena de texto, vocales con tilde, espacios separados\\\\nComposicion: 0{A-z| |}60z',
  `correo_electronico` varchar(100) NOT NULL COMMENT 'Descripción: Datos alusivos al correo electrónico de la persona\\\\\\\\nNaturaleza: Cualitativo\\\\\\\\nDominio: Cadena de caracteres\\\\\\\\nComposición:\\\\\\\\nCorreo Electrónico = [Usuario, Dominio, Extensión]',
  `contrasena` varchar(128) NOT NULL COMMENT 'Descripción: Clave de seguridad reservada la cual permite un acceso seguro al sistema.\\\\nNaturaleza:Cualitativo\\\\nDominio: Caracteres alfanumericos\\\\nComposición: 0{A-z|0-9}40',
  `estatus` enum('Activo','Inactivo') NOT NULL COMMENT 'Descripcion: Dato de Auditoria que define el estatus actual del regitro, siendo 0 para un datos no activos y 1 para datos activos para uso en el sistema\\\\\\\\\\\\\\\\nNaturaleza: Cuantativo\\\\\\\\\\\\\\\\nDominio: Booleano\\\\\\\\\\\\\\\\nComposicion: [0|1]\\\\\\\\\\\\\\\\n',
  `fecha_registro` datetime NOT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de creacion del registro\\\\\\\\\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\\\\\\\\\nComposicion:\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\nAño = 4{0-9}4\\\\\\\\\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\nHora = [00|01|...|23]\\\\\\\\\\\\\\\\nMinutos = [00|01|...|59]\\\\\\\\\\\\\\\\nSeguntodos = [00|01|...|59]\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\nFecha_Registro= Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  `fecha_actualizacion` datetime DEFAULT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de la ultima modificacion del registro\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\nComposicion:\\\\\\\\n\\\\\\\\n\\\\\\\\nAño = 4{0-9}4\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\n\\\\\\\\nHora = [00|01|...|23]\\\\\\\\nMinutos = [00|01|...|59]\\\\\\\\nSeguntodos = [00|01|...|59]\\\\\\\\n\\\\\\\\nFecha_Actualizacion = Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_nombre_usuario` (`nombre_usuario`),
  UNIQUE KEY `uq_correo_electronico` (`correo_electronico`),
  KEY `persona_id` (`persona_id`),
  CONSTRAINT `tbb_usuarios_ibfk_1` FOREIGN KEY (`persona_id`) REFERENCES `tbb_personas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=790 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Representa a una persona registrada en el sistema con credenciales de acceso. Depende de la entidad Persona, ya que hereda sus datos básicos.';
