CREATE TABLE `tbb_personas` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'Descripcion: Atributo identificador numero auto incremental que distingue de manera unica a la persona. \\\\nNaturaleza: Cuantitativo\\\\nDominio: Enteos positivos\\\\nComposicion: 1{0-9}',
  `titulo_cortesia` varchar(20) DEFAULT NULL COMMENT 'Descripcion: Abreviatur o Palabra de Cortesia para dirigirse de manera formal a la persona, por ejemplo:Sr., Sra.,Ing., Dra, etc.\\\\nNaturaleza: Cualitativa \\\\nDominio: Caracteres Alfanumericos y puntos (.)\\\\nComposicion: 0{A-Z|a-z|.}20',
  `nombre` varchar(80) NOT NULL COMMENT 'Descripcion: Valos asociado a la persona dentro de su registro civil\\\\\\\\nNaturaleza: Cualitativa \\\\\\\\nDominio: Caracteres Alfanumericos, vocales con tilde, espacios separados \\\\\\\\nComposicion: 0{A-Z|a-z| |}80',
  `primer_apellido` varchar(80) NOT NULL COMMENT 'Descripcion: Valos asociado a la persona dentro de su registro civil, generalmente conocido como Apellido Paterno\\\\\\\\nNaturaleza: Cualitativa \\\\\\\\nDominio: Caracteres Alfanumericos, vocales con tilde, espacios separados \\\\\\\\nComposicion: 0{A-Z|a-z| |}80',
  `segundo_apellido` varchar(80) DEFAULT NULL COMMENT 'Descripcion: Valos asociado a la persona dentro de su registro civil, generalmente conocido como Apellido Materno\\\\\\\\nNaturaleza: Cualitativa \\\\\\\\nDominio: Caracteres Alfanumericos, vocales con tilde, espacios separados \\\\\\\\nComposicion: 0{A-Z|a-z| |}80',
  `fecha_nacimiento` date NOT NULL COMMENT 'Descripcion: Fecha que determina la edad de la persona, indicado el dia, mes y año de natalicio\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\nComposicion:\\\\\\\\n\\\\\\\\nAño = 4{0-9}4\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\nFecha_Nacimiento = Año+''-''+Mes+''-''+Diaa',
  `fotografia` varchar(100) DEFAULT NULL COMMENT 'Descripcion: Nombre y extension del archivo de la imagen de portada de la persona.\\\\\\\\nNaturaleza: Cualitativa \\\\\\\\nDominio: Caracteres Alfanumericos, mas la extension permitida de imagenes como .jpg, .png, etc. \\\\\\\\nComposicion:\\\\\\\\n\\\\\\\\nNombre_Archivo = 0{A-z|0-9}96\\\\\\\\nExtension_Archivo = 0{A-z}4\\\\\\\\nFotografia = Nombre_Archivo+''-''+Extension_Archivo',
  `numero_telefonico` varchar(20) DEFAULT NULL COMMENT 'Descripción: Datos alusivos al número de teléfono de la persona\\\\nNaturaleza: Cualitativo\\\\nDominio: Cadena de caracteresTeléfono = [Código de País, Código de Área, Número de Teléfono, Extensión (opcional)]',
  `genero` enum('H','M','NB') NOT NULL COMMENT 'Descripcion: Datos alusivo al genero biologico de la persona\\\\\\\\nNaturaleza: Cualitativo\\\\\\\\nDominio: Conjunto de valoesr Permitidos\\\\\\\\nComposicion: \\\\\\\\n\\\\\\\\nGenero = [''H'',''M'',''N/B''] ',
  `tipo_sangre` enum('A_POSITIVO','A_NEGATIVO','B_POSITIVO','B_NEGATIVO','AB_POSITIVO','AB_NEGATIVO','O_POSITIVO','O_NEGATIVO') NOT NULL COMMENT 'Descripcion: Datos referentes al tipo y grupo sanguineo\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\nNaturaleza: Cualitativo\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\nDominio: Conjunto de valores Permitidos\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\nComposicion: \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\nTipo_Sangre = [''A_Positivo'', ''A_Negativo'', ''B_Positivo'', ''B_Negativo'', ''AB_Positivo'', ''AB_Negativo'', ''O_Positivo'', ''O_Negativo''] ',
  `estatus` enum('Activo','Inactivo') NOT NULL COMMENT 'Descripcion: Dato de Auditoria que define el estatus actual del regitro, siendo 0 para un datos no activos y 1 para datos activos para uso en el sistema\\\\\\\\nNaturaleza: Cuantativo\\\\\\\\nDominio: Booleano\\\\\\\\nComposicion: [0|1]\\\\\\\\n',
  `fecha_registro` datetime NOT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de creacion del registro\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\nComposicion:\\\\\\\\n\\\\\\\\nAño = 4{0-9}4\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\n\\\\\\\\nHora = [00|01|...|23]\\\\\\\\nMinutos = [00|01|...|59]\\\\\\\\nSeguntodos = [00|01|...|59]\\\\\\\\n\\\\\\\\nFecha_Registro= Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  `fecha_actualizacion` datetime DEFAULT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de la ultima modificacion del registro\\\\nNaturaleza: Cuantitativo\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\nComposicion:\\\\n\\\\n\\\\nAño = 4{0-9}4\\\\nMes =  [01|02|...|12]\\\\nDia =  [01|02|..|31]\\\\n\\\\nHora = [00|01|...|23]\\\\nMinutos = [00|01|...|59]\\\\nSeguntodos = [00|01|...|59]\\\\n\\\\nFecha_Actualizacion = Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  PRIMARY KEY (`id`),
  KEY `ix_tbb_personas_id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=796 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Esta tabla almacenara los datos de las personas asociadas a los usuarios de la plataforma de administracion de gimnasio, es importante denotar que la presona es una superentidad de : USUARIOS';
