CREATE TABLE `tbc_sucursales` (
  `Id` int NOT NULL AUTO_INCREMENT COMMENT 'Descripción: Atributo identificador entero autoincremental que distingue de manera única a la sucursal.<br>Dominio: Cuantitativo<br>Naturaleza: Enteros Positivos<br>Composición: 1 (0-9)',
  `Nombre` varchar(60) NOT NULL COMMENT 'Descripción: Contiene el nombre de la sucursal registrada en el sistema. Es un atributo obligatorio para identificar a la sucursal.\\\\\\\\<br>Naturaleza:Cualitativa.\\\\\\\\<br>Dominio: Caracteres alfabéticos (A-Z, a-z) y espacios en blanco.\\\\\\\\<br>Composición: 0{A-z| |}60',
  `Direccion` varchar(150) NOT NULL COMMENT 'Descripción: Guarde la dirección física donde se encuentra la sucursal.\\\\\\\\<br>Naturaleza:Cualitativa.\\\\\\\\<br>Dominio: Caracteres alfanuméricos y símbolos de dirección y espacios en blanco.\\\\\\\\<br>Composición: 0{A-z| |0-9}150',
  `Responsable_Id` int NOT NULL COMMENT 'Descripción:Identificador del Gerente responsable de la sucursal. Hace referencia a la tabla Usuario_Roles.<br>Naturaleza: Cuantitativa<br>Dominio:Números enteros positivos<br>Composición:1 a 9 dígitos (0-9)',
  `Capacidad_Maxima` int NOT NULL COMMENT 'Descripción:Número máximo de clientes permitidos en la sucursal.\\\\nNaturaleza:Cuantitativa\\\\nDominio:Números enteros positivos\\\\nComposición:1 a 9 dígitos (0-9)',
  `Horario_Disponibilidad` text NOT NULL COMMENT 'Descripción:Contiene información detallada sobre los horarios de apertura y cierre de la sucursal.\nNaturaleza:Cualitativa\nDominio:Texto libre con caracteres alfanuméricos y símbolos\nComposición: 0{A-z|0-9}255',
  `Estatus` tinyint(1) NOT NULL COMMENT 'Descripción:Indica si la sucursal está activa (1) o inactiva (0).\\\\\\\\<br>Naturaleza:Cuantitativa\\\\\\\\<br>Dominio: Valores binarios (0 o 1)\\\\\\\\<br>Composición:1 dígito (0,1)',
  `Fecha_Registro` datetime NOT NULL COMMENT 'Descripción: Indica la fecha y hora exacta en que la sucursal fue registrada en el sistema. Esta información es importante para llevar un control de la antigüedad de la sucursal y su historial de operaciones.\\\\nNaturaleza: Cuantitativa\\\\nDominio:Conjunto de valores permitidos: (Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto).\\\\nComposicion:\\\\\\\\<br>\\\\\\\\<br>Año = 4{0-9}4\\\\\\\\<br>Mes = [01|02|...|12]\\\\\\\\<br>Dia = [01|02|..|31]\\\\\\\\<br>\\\\\\\\<br>Hora = [00|01|...|23]\\\\\\\\<br>Minutos = [00|01|...|59]\\\\\\\\<br>Seguntodos = [00|01|...|59]\\\\\\\\<br>\\\\\\\\<br>Fecha_Registro= Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  `Fecha_Actualizacion` datetime DEFAULT NULL COMMENT 'Descripción: Última fecha y hora en que se modificó la información de la sucursal.\\nNaturaleza: Cuantitativa\\nDominio:Conjunto de valores permitidos: (Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto).\\nComposicion:\\\\<br>\\\\<br>Año = 4{0-9}4\\\\<br>Mes = [01|02|...|12]\\\\<br>Dia = [01|02|..|31]\\\\<br>\\\\<br>Hora = [00|01|...|23]\\\\<br>Minutos = [00|01|...|59]\\\\<br>Seguntodos = [00|01|...|59]\\\\<br>\\\\<br>Fecha_Actualización= Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  PRIMARY KEY (`Id`),
  KEY `Responsable_Id` (`Responsable_Id`),
  CONSTRAINT `tbc_sucursales_ibfk_1` FOREIGN KEY (`Responsable_Id`) REFERENCES `tbd_usuarios_roles` (`Usuario_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Representa una unidad operativa dentro del negocio, encargada de ofrecer servicios o productos.';
