CREATE TABLE `tbc_roles` (
  `ID` int NOT NULL AUTO_INCREMENT COMMENT 'Descripcion: Atributo identificador numero auto incremental que distingue de manera unica un rol. \nNaturaleza: Cuantitativo\nDominio: Enteros positivos\nComposicion: 1{0-9}',
  `Nombre` varchar(60) NOT NULL COMMENT 'Descripcion: Abreviatura o Palabra que determina el cargo que tiene una persona o usuario dentro del gimnasio, cargos tales como cliente, colaborador, administrador, entrenador... etc.\nNaturaleza: Cualitativa\nDominio: Caracteres Alfanumericos y puntos (.)\nComposicion: 0{A-Z|a-z|.}60',
  `Descripcion` text NOT NULL COMMENT 'Descripción: Información que dicta lo que realiza este rol.\nNaturaleza: Cualitativo\nDominio: Caracteres alfabéticos, tildes y signos de puntuación\nComposición: {A-z| | .|,|}',
  `Estatus` tinyint(1) NOT NULL COMMENT 'Descripcion: Dato de Auditoria que define el estatus actual del regitro, siendo 0 para un datos no activos y 1 para datos activos para uso en el sistema\\\\\\\\nNaturaleza: Cuantativo\\\\\\\\nDominio: Booleano\\\\\\\\nComposicion: [0|1]\\\\\\\\n',
  `Fecha_Registro` datetime NOT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de creacion del registro\\\\\\\\nNaturaleza: Cuantitativo\\\\\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\\\\\nComposicion:\\\\\\\\n\\\\\\\\nAño = 4{0-9}4\\\\\\\\nMes =  [01|02|...|12]\\\\\\\\nDia =  [01|02|..|31]\\\\\\\\n\\\\\\\\nHora = [00|01|...|23]\\\\\\\\nMinutos = [00|01|...|59]\\\\\\\\nSeguntodos = [00|01|...|59]\\\\\\\\n\\\\\\\\nFecha_Registro= Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  `Fecha_Actualizacion` datetime DEFAULT NULL COMMENT 'Descripcion: Dato de Auditoria que documenta la fecha y hora de la ultima modificacion del registro\\\\nNaturaleza: Cuantitativo\\\\nDominio: Numeros Enteros Positivos imitados por el calendario y limites de mes y/o año bisiesto.\\\\nComposicion:\\\\n\\\\n\\\\nAño = 4{0-9}4\\\\nMes =  [01|02|...|12]\\\\nDia =  [01|02|..|31]\\\\n\\\\nHora = [00|01|...|23]\\\\nMinutos = [00|01|...|59]\\\\nSeguntodos = [00|01|...|59]\\\\n\\\\nFecha_Actualizacion = Año+''-''+Mes+''-''+Dia+''-''+Hora+''-''+Munutos+''-''+Segundos',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Define los permisos y responsabilidades que un usuario puede tener dentro del sistema, determinando su nivel de acceso y acciones permitidas.';
